FROM golang:1.26-alpine

RUN apk add --no-cache git ca-certificates tzdata \
    && go install github.com/air-verse/air@latest

WORKDIR /app

EXPOSE 8080

CMD ["sh", "-c", "go mod download && air -c .air.toml"]
