CREATE TABLE clients (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    api_endpoint VARCHAR(512) NOT NULL COMMENT '推送地址',
    api_key VARCHAR(255) NOT NULL COMMENT 'API Key',
    hmac_secret VARCHAR(255) NOT NULL COMMENT 'HMAC签名密钥',
    callback_url VARCHAR(512) COMMENT '客户回调地址',
    config JSON COMMENT '扩展配置',
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_api_key (api_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
