CREATE TABLE tickets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ticket_no VARCHAR(32) NOT NULL COMMENT 'TK-YYYYMMDD-NNNN',
    alert_source_id BIGINT UNSIGNED NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    alert_raw JSON NOT NULL,
    alert_parsed JSON,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    severity VARCHAR(16) NOT NULL DEFAULT 'info' COMMENT 'critical | warning | info',
    status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending | in_progress | completed | failed | cancelled',
    client_id BIGINT UNSIGNED,
    external_id VARCHAR(128) COMMENT '客户侧工单ID',
    callback_data JSON,
    fingerprint VARCHAR(64) COMMENT '告警指纹',
    timeout_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ticket_no (ticket_no),
    KEY idx_status (status),
    KEY idx_client_id (client_id),
    KEY idx_alert_source_id (alert_source_id),
    KEY idx_fingerprint (fingerprint),
    KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
